In [1]:
import numpy as np
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
arr+1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr+1998

array([1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007])

In [6]:
1/arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111])

In [7]:
arr**arr

array([        1,         4,        27,       256,      3125,     46656,
          823543,  16777216, 387420489], dtype=int32)

In [8]:
arr*arr

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [9]:
arr_2d=arr.reshape(3,3)
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr1 = np.arange(0,8)
arr_4d=arr1.reshape(4,2)
arr_4d

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [23]:
arr_4d*arr_4d

array([[ 0,  1],
       [ 4,  9],
       [16, 25],
       [36, 49]])

In [25]:
arr_1d=np.array([1,2,3])
arr_2d*arr_1d

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [26]:
arr_3d=np.array([1,2])
arr_4d*arr_3d

array([[ 0,  2],
       [ 2,  6],
       [ 4, 10],
       [ 6, 14]])

In [27]:
arr_2d/arr_2d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
arr_4d/arr_3d

array([[0. , 0.5],
       [2. , 1.5],
       [4. , 2.5],
       [6. , 3.5]])

In [29]:
np.sqrt(arr_4d)

array([[0.        , 1.        ],
       [1.41421356, 1.73205081],
       [2.        , 2.23606798],
       [2.44948974, 2.64575131]])

In [30]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [31]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [32]:
np.exp(arr_4d)

array([[1.00000000e+00, 2.71828183e+00],
       [7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03]])

In [33]:
np.sin(arr_2d)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [34]:
np.log(arr_2d)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [35]:
np.sin(arr_4d)

array([[ 0.        ,  0.84147098],
       [ 0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ]])

In [36]:
np.log(arr_3d)

array([0.        , 0.69314718])

In [38]:
arran = np.arange(0,11)
arran

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
np.insert(arran,-1,10)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 10])

In [44]:
np.insert(arr,5,10)

array([ 1,  2,  3,  4,  5, 10,  6,  7,  8,  9])

In [45]:
np.insert(arr,-5,10)

array([ 1,  2,  3,  4, 10,  5,  6,  7,  8,  9])

In [46]:
np.delete(arr,-1)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
np.delete(arr,7)

array([1, 2, 3, 4, 5, 6, 7, 9])

In [48]:
np.append(arr,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11])

In [49]:
np.append(arr,100)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 100])

In [70]:
a= np.array([[1,2],[3,4]])
b = np.array([[5,6]])
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [74]:
c= np.array([[1,2,3],[4,5,6],[7,8,9]])
d = np.array([[2,4,6]])
np.concatenate((c,d), axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [2, 4, 6]])

In [72]:
np.concatenate((a,b.T),axis =1)

array([[1, 2, 3, 2],
       [4, 5, 6, 4],
       [7, 8, 9, 6]])

In [75]:
np.concatenate((c,d.T),axis =1)

array([[1, 2, 3, 2],
       [4, 5, 6, 4],
       [7, 8, 9, 6]])

In [77]:
np.concatenate((a,b), axis = None)

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 2, 4, 6])

In [78]:
np.where(arr>5,1,arr)

array([1, 2, 3, 4, 5, 1, 1, 1, 1])

In [87]:
np.where(arran>10,1,arran)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
np.where(arr_4d*0.5>4,arr_4d,arr_4d)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])